version: '3.9'

services:
  web:
    image: nginx:stable
    restart: always
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./portalsettings/portal/static:/data/static"
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    build: ./portalsettings
    restart: always
    command: uvicorn portalsettings.asgi:application --reload --host 0.0.0.0 --port 8000
    volumes:
      - "./portalsettings:/app"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.8-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"